# Generated by Django 5.0.4 on 2024-05-03 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_email', models.EmailField(max_length=23)),
                ('User_number', models.BigIntegerField()),
                ('amount_required', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currant_Date', models.DateTimeField(auto_now_add=True)),
                ('loan_term', models.IntegerField()),
                ('approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repayment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('repayment_date', models.DateField()),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Techdomapp.loan_details')),
            ],
        ),
    ]
