# Generated by Django 5.0.4 on 2024-05-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Techdomapp', '0002_alter_loan_details_user_alter_loanrepayment_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_details',
            name='The_Date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
