# Generated by Django 5.0.4 on 2024-05-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Techdomapp', '0003_loan_details_the_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_details',
            name='The_Date',
            field=models.DateTimeField(),
        ),
    ]
