# Generated by Django 5.0.4 on 2024-05-04 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Techdomapp', '0004_alter_loan_details_the_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan_details',
            name='The_Date',
        ),
    ]
